# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 04:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Choose the file to upload.', upload_to='%Y/%m/%d')),
                ('password_set', models.BooleanField(default=False, help_text='Do you want to set any password to the uploaded file')),
                ('password', models.CharField(blank=True, help_text='Password of the file', max_length=20, null=True)),
                ('expiry_date', models.DateField(default=datetime.date(2017, 3, 12), help_text='Choose the expiry date of the file. NOTE: By default, the file would expire after 7 days of uploading')),
                ('public', models.BooleanField(default=False, help_text='Do you want the file to appear in the public repo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
