# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='password_set',
            field=models.BooleanField(default=False),
        ),
    ]
