# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20161220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='Public', max_length=100),
        ),
    ]
