# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20161222_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2016, 12, 29)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='Uploads/%Y/%m/%d'),
        ),
    ]
