# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20161222_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
