# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 19:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20161222_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.date(2016, 12, 31), help_text='Choose the expiry date of the file. NOTE: By default, the file would expire after 7 days of uploading'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Choose the file to upload.', upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='file',
            name='password',
            field=models.CharField(blank=True, help_text='Password of the file', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='password_set',
            field=models.BooleanField(default=False, help_text='Do you want to set any password to the uploaded file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False, help_text='Do you want the file to appear in the public repo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(default='PUBLIC', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
