# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20161224_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2016, 12, 31), help_text='Choose the expiry date of the file. NOTE: By default, the file would expire after 7 days of uploading'),
        ),
    ]
