# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20161227_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
